// Generated by CodiumAI

describe('Section', () => {
  // Each feature item contains an image, title, and description
  it('should display the correct image, title, and description for each feature item', () => {
    // Get all the feature items
    const featureItems = document.querySelectorAll('.feature-item');

    // Check if there are three feature items
    expect(featureItems.length).toBe(3);

    // Check the first feature item
    const firstFeatureItem = featureItems[0];
    const firstFeatureItemImage = firstFeatureItem.querySelector('.feature-icon');
    const firstFeatureItemTitle = firstFeatureItem.querySelector('.feature-item-title');
    const firstFeatureItemDescription = firstFeatureItem.querySelector('p');

    expect(firstFeatureItemImage.src).toContain('icon-chat.png');
    expect(firstFeatureItemTitle.textContent).toBe('You are our #1 priority');
    expect(firstFeatureItemDescription.textContent).toBe('Need to talk to a representative? You can get in touch through our 24/7 chat or through a phone call in less than 5 minutes.');

    // Check the second feature item
    const secondFeatureItem = featureItems[1];
    const secondFeatureItemImage = secondFeatureItem.querySelector('.feature-icon');
    const secondFeatureItemTitle = secondFeatureItem.querySelector('.feature-item-title');
    const secondFeatureItemDescription = secondFeatureItem.querySelector('p');

    expect(secondFeatureItemImage.src).toContain('icon-money.png');
    expect(secondFeatureItemTitle.textContent).toBe('More savings means higher rates');
    expect(secondFeatureItemDescription.textContent).toBe('The more you save with us, the higher your interest rate will be!');

    // Check the third feature item
    const thirdFeatureItem = featureItems[2];
    const thirdFeatureItemImage = thirdFeatureItem.querySelector('.feature-icon');
    const thirdFeatureItemTitle = thirdFeatureItem.querySelector('.feature-item-title');
    const thirdFeatureItemDescription = thirdFeatureItem.querySelector('p');

    expect(thirdFeatureItemImage.src).toContain('icon-security.png');
    expect(thirdFeatureItemTitle.textContent).toBe('Security you can trust');
    expect(thirdFeatureItemDescription.textContent).toBe('We use top of the line encryption to make sure your data and money is always safe.');
  });
});
